### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by Fastidious** [thehowl/ip.zxq.co#1]
How to build this? Looks neat!

**Comment by Fastidious** [comment]
Figured out. It would be nice if no IP is entered, it would use the `REMOTE_ADDR` instead.

**Comment by thehowl** [comment]
Perhaps will do that tomorrow morning ~

On 27 September 2015 01:11:20 CEST, Fastidious notifications@github.com wrote:

> Figured out. It would be nice if no IP is entered, it would use the
> `REMOTE_ADDR` instead.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TheHowl/ip.zxq.co/issues/1#issuecomment-143503669

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Fastidious** [comment]
👍🏻

**Comment by thehowl** [comment]
Done as of f4ac205468ad3cb3c323315faf1148f7f17a42c9

**Comment by thehowl** [comment]
(still not live yet, as I want to fix #2 first, but it will be hopefully soon)

**Comment by thehowl** [comment]
(now live)

**Comment by Fastidious** [comment]
Excellent! Will check as soon as I get home.
