### ISSUE TITLE
Organisation info ?

### ISSUE THREAD

**Issue by crazy-max** [thehowl/ip.zxq.co#3]
Hi,

It would be nice if you can provide the organisation like ipinfo does :

http://ipinfo.io/8.8.8.8/json

```json
{
  "ip": "8.8.8.8",
  "hostname": "google-public-dns-a.google.com",
  "city": "Mountain View",
  "region": "California",
  "country": "US",
  "loc": "37.3860,-122.0840",
  "org": "AS15169 Google Inc.",
  "postal": "94035",
  "phone": "650"
}
```

**Comment by thehowl** [comment]
While I do understand that this feature would be quite useful, unfortunately this would require getting the info from an external data source, as it is not provided with the GeoLite database. The goal of the project is to be able to use little resources, to be fast, and not to have "exotic" features, so I'm afraid that I won't be working on this. If someone is able to work out how to implement it with a maximum of a 10% increase in response times (on an HDD) I am willing to include it in the project through a pull request.

**Comment by crazy-max** [comment]
Ok no problem i understand, thanks for your answer
