### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by gcpmusic** [thehowl/ip.zxq.co#5]
Today I start to have this issue:

gCs-MacBook-Pro:~ gc$ curl ip.zxq.co/8.8.8.8
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

Was working fine for months. Any help?
Thank you in advance.

**Comment by thehowl** [comment]
The service was moved to a new system where nginx was configured to redirect all http requests to https. I've made an exception, for backwards compatibility, to allow http access on ip.zxq.co - although you should use https in your application and should also follow redirects as a general advice. Thank you for the issue nonetheless!

**Comment by gcpmusic** [comment]
Many thanks  for the reply Morgan. However, your suggestion works fine in a browser but not within a script using curl. Any suggestion to let it work in the terminal using curl command?

Thanks in advance.

**Comment by thehowl** [comment]
it's as simple as `curl https://ip.zxq.co` for HTTPS - and `curl -L ip.zxq.co` (http) to follow redirects :)

**Comment by gcpmusic** [comment]
Thanks Morgan
when I tried https://ip.zxq.co I didnt realise I had a network disservice. I am sorry. Works great now.
All the best.
